---
framework: terraform
skip-check:
  - CKV2_AWS_4
  - CKV2_AWS_6
  - CKV2_AWS_29
  - CKV2_AWS_40
  - CKV2_AWS_51
  - CKV_AWS_18
  - CKV_AWS_76
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_118
  - CKV_AWS_120
  - CKV_AWS_129
  - CKV_AWS_144
  - CKV_AWS_157
  - CKV_AWS_161
  - CKV_AWS_173
  - CKV_AWS_225
  - CKV_AWS_272
  - CKV_AWS_59
